"""Shared contracts v0.1: import from src.operator.contracts."""

from .ports import BrowserPort, ChannelPort, DataSourcePort, LedgerPort, LLMPort
from .primitives import (
    ActionResult,
    Contract,
    FieldResult,
    FieldSpec,
    FillAction,
    FillReport,
    JobStatus,
    PageState,
    SubmissionResult,
)
from .state import (
    Answer,
    AnswerLibrary,
    ApprovalState,
    Command,
    DataSnapshot,
    Event,
    Goal,
    JobPosting,
    JobState,
    Profile,
    ReviewSnapshot,
    Rules,
    RunState,
    RunStatus,
    Upload,
    Usage,
)

CONTRACT_VERSION = "0.1"

__all__ = [
    "CONTRACT_VERSION",
    "ActionResult",
    "Answer",
    "AnswerLibrary",
    "ApprovalState",
    "BrowserPort",
    "ChannelPort",
    "Command",
    "Contract",
    "DataSnapshot",
    "DataSourcePort",
    "Event",
    "FieldResult",
    "FieldSpec",
    "FillAction",
    "FillReport",
    "Goal",
    "JobPosting",
    "JobState",
    "JobStatus",
    "LLMPort",
    "LedgerPort",
    "PageState",
    "Profile",
    "ReviewSnapshot",
    "Rules",
    "RunState",
    "RunStatus",
    "SubmissionResult",
    "Upload",
    "Usage",
]
